/*
Floating Roses Animation (GSAP v1)
Stops after 2 minutes
*/

TweenLite.set("#container", { perspective: 600 });
TweenLite.set("img", { xPercent: "-50%", yPercent: "-50%" });

var total = 30;
var warp = document.getElementById("container"),
    w = window.innerWidth,
    h = window.innerHeight;

var dots = [];

// Create dots
for (let i = 0; i < total; i++) { 
  var Div = document.createElement('div');
  
  TweenLite.set(Div, {
    attr: { class: 'dot' },
    x: R(0, w),
    y: R(-200, -150),
    z: R(-200, 200)
  });
  
  warp.appendChild(Div);
  dots.push(Div);
  animm(Div);
}

// Animation function
function animm(elm) {   
  TweenMax.to(elm, R(6, 15), {
    y: h + 100,
    ease: Linear.easeNone,
    repeat: -1,
    delay: -15
  });

  TweenMax.to(elm, R(4, 8), {
    x: '+=100',
    rotationZ: R(0, 180),
    repeat: -1,
    yoyo: true,
    ease: Sine.easeInOut
  });

  TweenMax.to(elm, R(2, 8), {
    rotationX: R(0, 360),
    rotationY: R(0, 360),
    repeat: -1,
    yoyo: true,
    ease: Sine.easeInOut,
    delay: -5
  });
}

// Random function
function R(min, max) {
  return min + Math.random() * (max - min);
}

setTimeout(function () {
  dots.forEach(dot => {
    TweenMax.to(dot, 1, { opacity: 0, onComplete: () => dot.remove() });
  });
}, 12000);


const data = [
    { lang: "Urdu (Indo-Aryan)", word: "اسرا آمرین (Asra Amreen)" },
    { lang: "Hindi", word: "असरा अमरीन" },
    { lang: "Telugu", word: "అస్రా అమ్రీన్" },
    { lang: "Tamil", word: "அஸ்ரா அம்ரீன்" },

    { lang: "braille", word: "⠁⠎⠗⠁ ⠁⠍⠗⠑⠑⠝" },
    { lang: "morse", word: ".- ... .-. .- / .- -- .-. . . -." },

    { lang: "Aari (Omotic)", word: "Asra Amreen" },
{ lang: "Abanyom (Bantu)", word: "Asra Amreen" },
{ lang: "Abujmaria (Dravidian)", word: "असरा अमरीन" },
{ lang: "Adele (Kwa)", word: "Asra Amreen" },
{ lang: "Afar (Cushitic)", word: "Asra Amreen" },
{ lang: "Afrikaans (Germanic)", word: "Asra Amreen" },
{ lang: "Aini (Turkic)", word: "Асра Амрин" },
{ lang: "Ainu (language isolate)", word: "アスラ アムリーン" },
{ lang: "Akan (Kwa)", word: "Asra Amreen" },
{ lang: "Akawaio (Carib)", word: "Asra Amreen" },
{ lang: "Albanian (Indo-European)", word: "Asra Amreen" },
{ lang: "Aleut (Eskimo–Aleut)", word: "Asra Amreen" },
{ lang: "Algonquin (Algonquian)", word: "Asra Amreen" },
{ lang: "Alsatian (Germanic)", word: "Asra Amreen" },
{ lang: "Altay (Turkic)", word: "Асра Амрин" },
{ lang: "Amdang (Nilo-Saharan)", word: "Asra Amreen" },
{ lang: "Amharic (Semitic)", word: "አስራ አምሪን" },
{ lang: "Anda (Khoisan)", word: "Asra Amreen" },
{ lang: "Angika (Indo-Aryan)", word: "असरा अमरीन" },
{ lang: "Anyin (Kwa)", word: "Asra Amreen" },
{ lang: "Ao (Tibeto-Burman)", word: "Asra Amreen" },
{ lang: "A-Pucikwar (Andamanese)", word: "Asra Amreen" },
{ lang: "Arabic (Semitic)", word: "اسرا آمرین" },
{ lang: "Aragonese (Romance)", word: "Asra Amreen" },
{ lang: "Aramaic (Semitic)", word: "ܐܣܪܐ ܐܡܪܝܢ" },
{ lang: "Are (Malayo-Polynesian)", word: "Asra Amreen" },
{ lang: "Argobba (Semitic)", word: "አስራ አምሪን" },
{ lang: "Armenian (Indo-European)", word: "Ասրա Ամրին" },
{ lang: "Arvanitic (Indo-European)", word: "Ασρα Αμριν" },
{ lang: "Ashkun (Indo-Iranian)", word: "اسرا امرین" },
{ lang: "Asi (Malayo-Polynesian)", word: "Asra Amreen" },
{ lang: "Assamese (Indo-Iranian)", word: "অসৰা আমৰীন" },
{ lang: "Asturian (Romance)", word: "Asra Amreen" },
{ lang: "Ateso or Teso (Nilotic)", word: "Asra Amreen" },
{ lang: "A’Tong (Tibeto-Burman)", word: "Asra Amreen" },
{ lang: "Auslan (Signing)", word: "[fingerspelled: ASRA AMREEN]" },
{ lang: "Avestan (Indo-Iranian)", word: "𐬀𐬯𐬭𐬀 𐬀𐬨𐬭𐬉𐬥" },
{ lang: "Awadhi (Indo-Iranian)", word: "असरा अमरीन" },
{ lang: "Aymara (Aymaran)", word: "Asra Amreen" },
{ lang: "Azerbaijani (Turkic)", word: "Asra Amreen" },

{ lang: "Badaga (Dravidian)", word: "ಅಸ್ರಾ ಅಮ್ರೀನ್" },
{ lang: "Badeshi (Indo-Iranian)", word: "असरा अमरीन" },
{ lang: "Bahnar (Austroasiatic)", word: "Asra Amreen" },
{ lang: "Balochi (Indo-Iranian)", word: "اسرا آمرین" },
{ lang: "Balti (Tibeto-Burman)", word: "اسرا آمرین" },
{ lang: "Bartangi (Iranian)", word: "Асра Амрин" },
{ lang: "Basaa (Bantu)", word: "Asra Amreen" },
{ lang: "Bashkardi (Iranian)", word: "اسرا امرین" },
{ lang: "Bashkir (Turkic)", word: "Асра Амрин" },
{ lang: "Basque (Isolated)", word: "Asra Amreen" },
{ lang: "Bats (North Caucasian)", word: "Асра Амрин" },
{ lang: "Beja (Cushitic)", word: "Asra Amreen" },
{ lang: "Belarusian (Slavic)", word: "Асра Амрын" },
{ lang: "Belhare (Tibeto-Burman)", word: "Asra Amreen" },
{ lang: "Bemba (Bantu)", word: "Asra Amreen" },
{ lang: "Bengali (Indo-Aryan)", word: "অসরা আমরীন" },
{ lang: "Berta (Nilo-Saharan)", word: "Asra Amreen" },
{ lang: "Bete (Niger–Congo)", word: "Asra Amreen" },
{ lang: "Bhili (Indo-Aryan)", word: "असरा अमरीन" },
{ lang: "Bhojpuri (Indo-Aryan)", word: "असरा अमरीन" },
{ lang: "Bikol (Malayo-Polynesian)", word: "Asra Amreen" },
{ lang: "Bikya or Furu (Bantu)", word: "Asra Amreen" },
{ lang: "Bissa (Mande)", word: "Asra Amreen" },
{ lang: "Blackfoot (Algonquian)", word: "Asra Amreen" },
{ lang: "Bodo (Bodo)", word: "असरा अमरीन" },
{ lang: "Bonan or Paoan (Mongolic)", word: "Асра Амрин" },
{ lang: "Bororo (Bororoan)", word: "Asra Amreen" },
{ lang: "Bosnian (Slavic)", word: "Asra Amreen" },
{ lang: "Brahui (Dravidian)", word: "اسرا آمرین" },
{ lang: "Breton (Celtic)", word: "Asra Amreen" },
{ lang: "Bua (Niger–Congo)", word: "Asra Amreen" },
{ lang: "Bukusu (Bantu)", word: "Asra Amreen" },
{ lang: "Bulgarian (Slavic)", word: "Асра Амрин" },
{ lang: "Bunjevac (Slavic)", word: "Asra Amreen" },
{ lang: "Burmese (Tibeto-Burman)", word: "အက်စ်ရာ အမ်ရင်း" },
{ lang: "Buryat (Mongolic)", word: "Асра Амрин" },

{ lang: "Caddo (Caddoan)", word: "Asra Amreen" },
{ lang: "Cahuilla (Uto-Aztecan)", word: "Asra Amreen" },
{ lang: "Cantonese (Sinitic)", word: "阿斯拉 阿姆林" },
{ lang: "Catalan (Romance)", word: "Asra Amreen" },
{ lang: "Cayuga (Iroquoian)", word: "Asra Amreen" },
{ lang: "Chaga or Kichagga (Bantu)", word: "Asra Amreen" },
{ lang: "Chakma (Indo-Aryan)", word: "𑄃𑄥𑄳𑄢𑄖 𑄃𑄟𑄳𑄢𑄨𑄚" },
{ lang: "Chenchu (Dravidian)", word: "అస్రా అమ్రీన్" },
{ lang: "Chenoua (Berber)", word: "Asra Amreen" },
{ lang: "Cherokee (Iroquoian)", word: "ᎠᏍᎳ ᎠᎻᎵᏂ" },
{ lang: "Cheyenne (Algonquian)", word: "Asra Amreen" },
{ lang: "Chickasaw (Muskogean)", word: "Asra Amreen" },
{ lang: "Chilcotin (Athabaskan)", word: "Asra Amreen" },
{ lang: "Chinese (Sinitic)", word: "阿斯拉 阿姆林" },
{ lang: "Chipewyan (Athabaskan)", word: "Asra Amreen" },
{ lang: "Chittagonian (Indo-Aryan)", word: "অসরা আমরীন" },
{ lang: "Choctaw (Muskogean)", word: "Asra Amreen" },
{ lang: "Chulym (Turkic)", word: "Асра Амрин" },
{ lang: "Church Slavonic (Slavic)", word: "Асра Амрин" },
{ lang: "Chuvash (Turkic)", word: "Асра Амрин" },
{ lang: "Cocoma or Cocama (Tupian)", word: "Asra Amreen" },
{ lang: "Cocopa (Hokan)", word: "Asra Amreen" },
{ lang: "Coeur d’Alene (Salishan)", word: "Asra Amreen" },
{ lang: "Comanche (Uto-Aztecan)", word: "Asra Amreen" },
{ lang: "Comorian (Bantu)", word: "Asra Amreen" },
{ lang: "Corsican (Romance)", word: "Asra Amreen" },
{ lang: "Cree (Algonquian)", word: "ᐊᔅᕋ ᐊᒻᕆᓐ" },
{ lang: "Croatian (Slavic)", word: "Asra Amreen" },
{ lang: "Czech (Slavic)", word: "Asra Amreen" },

{ lang: "Dagbani (Gur)", word: "Asra Amreen" },
{ lang: "Dahlik (Semitic)", word: "اسرا آمرین" },
{ lang: "Dalecarlian (Germanic)", word: "Asra Amreen" },
{ lang: "Dameli (Indo-Aryan)", word: "असरा अमरीन" },
{ lang: "Danish (Germanic)", word: "Asra Amreen" },
{ lang: "Dari-Persian (Iranian)", word: "اسرا آمرین" },
{ lang: "Daur or Dagur (Mongolic)", word: "Асра Амрин" },
{ lang: "Dhatki (Indo-Aryan)", word: "असरा अमरीन" },
{ lang: "Dida (Kru)", word: "Asra Amreen" },
{ lang: "Dioula or Jula (Mande)", word: "Asra Amreen" },
{ lang: "Dogri (Indo-Aryan)", word: "असरा अमरीन" },
{ lang: "Dolgan (Turkic)", word: "Асра Амрин" },
{ lang: "Duala (Bantu)", word: "Asra Amreen" },
{ lang: "Dungan (Sinitic)", word: "Асыра Амрин" },
{ lang: "Dutch (Germanic)", word: "Asra Amreen" },
{ lang: "Dzongkha (Tibeto-Burman)", word: "ཨསྲ་ཨམྲིན" },

{ lang: "Eastern Yugur (Mongolic)", word: "Асра Амрин" },
{ lang: "Edo (Nigeria)", word: "Asra Amreen" },
{ lang: "Efik (Nigeria)", word: "Asra Amreen" },
{ lang: "Egyptian Arabic (Semitic)", word: "اسرا آمرین" },
{ lang: "Ekoti (Bantu)", word: "Asra Amreen" },
{ lang: "English (Germanic)", word: "Asra Amreen" },
{ lang: "Erzya (Uralic)", word: "Асра Амрин" },
{ lang: "Esan (Nigeria)", word: "Asra Amreen" },
{ lang: "Estonian (Uralic)", word: "Asra Amreen" },
{ lang: "Even (Tungusic)", word: "Асра Амрин" },
{ lang: "Ewe (Volta–Niger)", word: "Asra Amreen" },
{ lang: "Extremaduran (Romance)", word: "Asra Amreen" },

{ lang: "Fang (Bantu)", word: "Asra Amreen" },
{ lang: "Finnish (Uralic)", word: "Asra Amreen" },
{ lang: "Fon (Volta–Niger)", word: "Asra Amreen" },
{ lang: "French (Romance)", word: "Asra Amreen" },
{ lang: "Frisian, North (Germanic)", word: "Asra Amreen" },
{ lang: "Frisian, West (Germanic)", word: "Asra Amreen" },
{ lang: "Friulian (Romance)", word: "Asra Amreen" },
{ lang: "Fur (Nilo-Saharan)", word: "Asra Amreen" },

{ lang: "Ga (Kwa)", word: "Asra Amreen" },
{ lang: "Gadaba (Dravidian)", word: "అస్రా అమ్రీన్" },
{ lang: "Gagauz (Turkic)", word: "Asra Amreen" },
{ lang: "Galician (Romance)", word: "Asra Amreen" },
{ lang: "Gallo (Romance)", word: "Asra Amreen" },
{ lang: "Gan (Sinitic)", word: "阿斯拉 阿姆林" },
{ lang: "Ganda (Bantu)", word: "Asra Amreen" },
{ lang: "Gangte (Tibeto-Burman)", word: "Asra Amreen" },
{ lang: "Garhwali (Indo-Aryan)", word: "असरा अमरीन" },
{ lang: "Gayo (Malayo-Polynesian)", word: "Asra Amreen" },
{ lang: "German (Germanic)", word: "Asra Amreen" },
{ lang: "Gikuyu or Kikuyu (Bantu)", word: "Asra Amreen" },
{ lang: "Gileki (Iranian)", word: "اسرا امرین" },
{ lang: "Goaria (Indo-Aryan)", word: "असरा अमरीन" },
{ lang: "Gondi (Dravidian)", word: "అస్రా అమ్రీన్" },
{ lang: "Gowro (Indo-Aryan)", word: "असरा अमरीन" },
{ lang: "Greek (Indo-European)", word: "Ασρα Αμριν" },
{ lang: "Guaraní (Tupian)", word: "Asra Amreen" },
{ lang: "Gujarati (Indo-Aryan)", word: "અસરા અમરીન" },
{ lang: "Gusii (Bantu)", word: "Asra Amreen" },
{ lang: "Gwichʼin (Athabaskan)", word: "Asra Amreen" },

{ lang: "Hadza (Language isolate)", word: "Asra Amreen" },
{ lang: "Haida (Na-Dené)", word: "Asra Amreen" },
{ lang: "Hakka (Sinitic)", word: "阿斯拉 阿姆林" },
{ lang: "Hän (Athabaskan)", word: "Asra Amreen" },
{ lang: "Harari (Semitic)", word: "አስራ አምሪን" },
{ lang: "Harauti (Indo-Aryan)", word: "असरा अमरीन" },
{ lang: "Harsusi (Semitic)", word: "اسرا آمرین" },
{ lang: "Harzani (Iranian)", word: "اسرا امرین" },
{ lang: "Hausa (Afro-Asiatic)", word: "Asra Amreen" },
{ lang: "Hebrew (Semitic)", word: "אסרא אמרין" },
{ lang: "Herero (Bantu)", word: "Asra Amreen" },
{ lang: "Hértevin (Semitic)", word: "אסרא אמרין" },
{ lang: "Hindi (Indo-Aryan)", word: "असरा अमरीन" },
{ lang: "Hixkaryana (Carib)", word: "Asra Amreen" },
{ lang: "Hmong (Hmong–Mien)", word: "Asra Amreen" },
{ lang: "Ho (Austroasiatic)", word: "Asra Amreen" },
{ lang: "Hobyót (Semitic)", word: "اسرا آمرین" },
{ lang: "Hopi (Uto-Aztecan)", word: "Asra Amreen" },
{ lang: "Hulaulá (Semitic)", word: "אסרא אמרין" },
{ lang: "Hungarian (Uralic)", word: "Asra Amreen" },
{ lang: "Hunsrik (Brazil)", word: "Asra Amreen" },

{ lang: "Iban (Malayo-Polynesian)", word: "Asra Amreen" },
{ lang: "Ibibio (Benue–Congo)", word: "Asra Amreen" },
{ lang: "Icelandic (Germanic)", word: "Asra Amreen" },
{ lang: "Ifè (Volta–Congo)", word: "Asra Amreen" },
{ lang: "Ili Turki (Turkic)", word: "Asra Amreen" },
{ lang: "Inari Sami (Uralic)", word: "Asra Amreen" },
{ lang: "Inuktitut (Eskimo–Aleut)", word: "ᐊᔅᕋ ᐊᒻᕆᓐ" },
{ lang: "Inupiaq (Eskimo–Aleut)", word: "Asra Amreen" },
{ lang: "Iraqw (Cushitic)", word: "Asra Amreen" },
{ lang: "Irula (Dravidian)", word: "அச்ரா அம்ரீன்" },
{ lang: "Istro-Romanian (Romance)", word: "Asra Amreen" },
{ lang: "Italian (Romance)", word: "Asra Amreen" },

{ lang: "Japanese (Japonic)", word: "アスラ アムリーン" },
{ lang: "Jaqaru (Aymaran)", word: "Asra Amreen" },
{ lang: "Jarai (Malayo-Polynesian)", word: "Asra Amreen" },
{ lang: "Juang (Austroasiatic)", word: "Asra Amreen" },
{ lang: "Jurchen (Tungusic)", word: "ᠠᠰᠷᠠ ᠠᠮᠷᠢᠨ" },

{ lang: "Kabyle (Berber)", word: "Asra Amreen" },
{ lang: "Kalasha (Indo-Aryan)", word: "असरा अमरीन" },
{ lang: "Kannada (Dravidian)", word: "ಅಸ್ರಾ ಅಮ್ರೀನ್" },
{ lang: "Karachay-Balkar (Turkic)", word: "Асра Амрин" },
{ lang: "Karagas (Turkic)", word: "Асра Амрин" },
{ lang: "Karaim (Turkic)", word: "Асра Амрин" },
{ lang: "Karakalpak (Turkic)", word: "Асра Амрин" },
{ lang: "Karelian (Uralic)", word: "Asra Amreen" },
{ lang: "Kashmiri (Indo-Aryan)", word: "اسرا آمرین" },
{ lang: "Kashubian (Slavic)", word: "Asra Amreen" },
{ lang: "Kazakh (Turkic)", word: "Асра Амрин" },
{ lang: "Kerek (Paleosiberian)", word: "Asra Amreen" },
{ lang: "Ket (Chukotko-Kamchatkan)", word: "Асра Амрин" },
{ lang: "Khakas (Turkic)", word: "Асра Амрин" },
{ lang: "Khalaj (Turkic)", word: "اسرا امرین" },
{ lang: "Khandeshi (Indo-Aryan)", word: "असरा अमरीन" },
{ lang: "Khanty or Ostyak (Uralic)", word: "Asra Amreen" },
{ lang: "Khasi (Austroasiatic)", word: "Asra Amreen" },
{ lang: "Khitan (Mongolic)", word: "ᠠᠰᠷᠠ ᠠᠮᠷᠢᠨ" },
{ lang: "Khmer (Austroasiatic)", word: "អស្រា អាម្រីន" },
{ lang: "Khmu (Austroasiatic)", word: "Asra Amreen" },
{ lang: "Khowar (Indo-Aryan)", word: "اسرا آمرین" },
{ lang: "Kildin Sami (Finnic)", word: "Asra Amreen" },
{ lang: "Kimatuumbi (Bantu)", word: "Asra Amreen" },
{ lang: "Kinyarwanda (Bantu)", word: "Asra Amreen" },
{ lang: "Kirombo (Bantu)", word: "Asra Amreen" },
{ lang: "Kirundi (Bantu)", word: "Asra Amreen" },
{ lang: "Kivunjo (Bantu)", word: "Asra Amreen" },
{ lang: "Kolami (Dravidian)", word: "అస్రా అమ్రీన్" },
{ lang: "Kongo or Kikongo (Bantu)", word: "Asra Amreen" },
{ lang: "Konkani (Indo-Aryan)", word: "असरा अमरीन" },
{ lang: "Koraga (Dravidian)", word: "ಅಸ್ರಾ ಅಮ್ರೀನ್" },
{ lang: "Korandje (Nilo-Saharan)", word: "Asra Amreen" },
{ lang: "Korean (isolated)", word: "아스라 아므린" },
{ lang: "Korku (Austroasiatic)", word: "Asra Amreen" },
{ lang: "Korwa (Austroasiatic)", word: "Asra Amreen" },
{ lang: "Kota (Dravidian)", word: "அஸ்ரா அம்ரீன்" },
{ lang: "Koya (Dravidian)", word: "అస్రా అమ్రీన్" },
{ lang: "Kui (Dravidian)", word: "ଅସ୍ରା ଅମ୍ରିନ୍" },
{ lang: "Kumauni (Indo-Aryan)", word: "असरा अमरीन" },
{ lang: "Kumyk (Turkic)", word: "Асра Амрин" },
{ lang: "Kumzari (Iranian)", word: "اسرا امرین" },
{ lang: "Kurdish (Iranian)", word: "Asra Amreen" },
{ lang: "Kusunda (isolate)", word: "Asra Amreen" },
{ lang: "Kxoe (Khoisan)", word: "Asra Amreen" },

{ lang: "Laal (unclassified)", word: "Asra Amreen" },
{ lang: "Ladakhi (Tibeto-Burman)", word: "ཨསྲ་ཨམྲིན" },
{ lang: "Ladin (Romance)", word: "Asra Amreen" },
{ lang: "Laki (Iranian)", word: "اسرا امرین" },
{ lang: "Larestani (Iranian)", word: "اسرا امرین" },
{ lang: "Latvian (Baltic)", word: "Asra Amreen" },
{ lang: "Leonese (Romance)", word: "Asra Amreen" },
{ lang: "Lepcha (Indo-Aryan)", word: "ᰀᰴᰴᰨᰮ ᰀᰴᰵᰮᰵᰲ" },
{ lang: "Ligbi or Ligby (Mande)", word: "Asra Amreen" },
{ lang: "Limbu (Indo-Aryan)", word: "ᤀᤎᤔᤖ ᤀᤎᤔᤖᤋᤖ" },
{ lang: "Limburgish (Germanic)", word: "Asra Amreen" },
{ lang: "Lingala (Bantu)", word: "Asra Amreen" },
{ lang: "Lipan Apache (Athabascan)", word: "Asra Amreen" },
{ lang: "Lishana Deni (Semitic)", word: "אסרא אמרין" },
{ lang: "Lithuanian (Baltic)", word: "Asra Amreen" },
{ lang: "Livonian or Liv (Uralic)", word: "Asra Amreen" },
{ lang: "Lombard (Romance)", word: "Asra Amreen" },
{ lang: "Lotha (Tibeto-Burman)", word: "Asra Amreen" },
{ lang: "Lower Sorbian (Slavic)", word: "Asra Amreen" },
{ lang: "Lozi or Silozi (Bantu)", word: "Asra Amreen" },
{ lang: "Ludic or Ludian (Uralic)", word: "Asra Amreen" },
{ lang: "Lunda or Chilunda (Bantu)", word: "Asra Amreen" },
{ lang: "Luo (Nilotic)", word: "Asra Amreen" },
{ lang: "Luri (Iranian)", word: "اسرا امرین" },
{ lang: "Lushootseed (Salishan)", word: "Asra Amreen" },
{ lang: "Lusoga or Soga (Bantu)", word: "Asra Amreen" },
{ lang: "Luvale (Bantu)", word: "Asra Amreen" },
{ lang: "Luwati (Indo-Iranian)", word: "اسرا آمرین" },
{ lang: "Luxembourgish (Germanic)", word: "Asra Amreen" },
{ lang: "Lycian (Indo-European)", word: "𐊀𐊐𐊓𐊀 𐊀𐊐𐊙𐊐𐊑" },
{ lang: "Lydian (Indo-European)", word: "𐤠𐤮𐤭𐤠 𐤠𐤬𐤭𐤮𐤮𐤭𐤮𐤭" },


{ lang: "Macedonian (Slavic)", word: "Асра Амрин" },
{ lang: "Magadhi (Indo-Aryan)", word: "असरा अमरीन" },
{ lang: "Maithili (Indo-Aryan)", word: "असरा अमरीन" },
{ lang: "Makhuwa or Makua (Bantu)", word: "Asra Amreen" },
{ lang: "Makhuwa-Meetto (Bantu)", word: "Asra Amreen" },
{ lang: "Malay (Malayo-Polynesian)", word: "Asra Amreen" },
{ lang: "Malayalam (Dravidian)", word: "അസ്രാ അമ്രീൻ" },
{ lang: "Maltese (Semitic)", word: "Asra Amreen" },
{ lang: "Mam (Mayan)", word: "Asra Amreen" },
{ lang: "Manchu (Tungusic)", word: "ᠠᠰᠷᠠ ᠠᠮᠷᠢᠨ" },
{ lang: "Mandaic (Semitic)", word: "אסרא אמרין" },
{ lang: "Mandarin (Sinitic)", word: "阿斯拉 阿姆林" },
{ lang: "Mandinka (Mande)", word: "Asra Amreen" },
{ lang: "Mansi or Vogul (Uralic)", word: "Асра Амрин" },
{ lang: "Manx (Celtic)", word: "Asra Amreen" },
{ lang: "Manyika (Bantu)", word: "Asra Amreen" },
{ lang: "Maori (Malayo-Polynesian)", word: "Asra Amreen" },
{ lang: "Marathi (Indo-Aryan)", word: "असरा अमरीन" },
{ lang: "Mari or Cheremis (Uralic)", word: "Асра Амрин" },
{ lang: "Maria (Dravidian)", word: "అస్రా అమ్రీన్" },
{ lang: "Masaba (Bantu)", word: "Asra Amreen" },
{ lang: "Maya (Mayan)", word: "Asra Amreen" },
{ lang: "Mehri or Mahri (Semitic)", word: "اسرا آمرین" },
{ lang: "Menominee (Algonquian)", word: "Asra Amreen" },
{ lang: "Meru or Kimeru (Bantu)", word: "Asra Amreen" },
{ lang: "Mirandese (Romance)", word: "Asra Amreen" },
{ lang: "Moghol (Mongolic)", word: "Асра Амрин" },
{ lang: "Mohawk (Iroquoian)", word: "Asra Amreen" },
{ lang: "Moksha (Uralic)", word: "Асра Амрин" },
{ lang: "Molengue (Bantu)", word: "Asra Amreen" },
{ lang: "Mon (Austroasiatic)", word: "အက်စ်ရာ အမ်ရင်း" },
{ lang: "Mongolian (Mongolic)", word: "ᠠᠰᠷᠠ ᠠᠮᠷᠢᠨ" },
{ lang: "Mono (Malayo-Polynesian)", word: "Asra Amreen" },
{ lang: "Mono (Ubangian)", word: "Asra Amreen" },
{ lang: "Mono (Uto-Aztecan)", word: "Asra Amreen" },
{ lang: "Montagnais (Algonquian)", word: "Asra Amreen" },
{ lang: "Montenegrin (Slavic)", word: "Asra Amreen" },
{ lang: "Motu (Malayo-Polynesian)", word: "Asra Amreen" },
{ lang: "Muher (Semitic)", word: "አስራ አምሪን" },
{ lang: "Mundari (Austroasiatic)", word: "Asra Amreen" },
{ lang: "Munji (Iranian)", word: "اسرا امرین" },
{ lang: "Muria (Dravidian)", word: "असरा अमरीन" },

{ lang: "Nǀu (Khoisan)", word: "Asra Amreen" },
{ lang: "Nafaanra (Senufo)", word: "Asra Amreen" },
{ lang: "Nagarchal (Dravidian)", word: "असरा अमरीन" },
{ lang: "Nahuatl (Uto-Aztecan)", word: "Asra Amreen" },
{ lang: "Nama (Khoisan)", word: "Asra Amreen" },
{ lang: "Nanai (Tungusic)", word: "Асра Амрин" },
{ lang: "Ndebele (Bantu)", word: "Asra Amreen" },
{ lang: "Ndonga (Bantu)", word: "Asra Amreen" },
{ lang: "Neapolitan (Romance)", word: "Asra Amreen" },
{ lang: "Negidal (Tungusic)", word: "Асра Амрин" },
{ lang: "Nepali (Indo-Aryan)", word: "असरा अमरीन" },
{ lang: "Ngumba (Bantu)", word: "Asra Amreen" },
{ lang: "Nias", word: "Asra Amreen" },
{ lang: "Niellim (Adamawa)", word: "Asra Amreen" },
{ lang: "Nogai (Turkic)", word: "Асра Амрин" },
{ lang: "Northern Sami (Uralic)", word: "Asra Amreen" },
{ lang: "Nuer (Nilotic)", word: "Asra Amreen" },
{ lang: "Nyabwa (Kru)", word: "Asra Amreen" },
{ lang: "Nyah Kur (Austroasiatic)", word: "Asra Amreen" },
{ lang: "Nyoro (Bantu)", word: "Asra Amreen" },

{ lang: "Odia (Indo-Aryan)", word: "ଅସ୍ରା ଅମ୍ରୀନ୍" },
{ lang: "Okinawan (Japonic)", word: "アスラ アムリーン" },
{ lang: "Omagua (Tupian)", word: "Asra Amreen" },
{ lang: "Ongota (Afro-Asiatic)", word: "Asra Amreen" },
{ lang: "Ormuri (Iranian)", word: "اسرا امرین" },
{ lang: "Oroch (Tungusic)", word: "Асра Амрин" },
{ lang: "Orok (Tungusic)", word: "Асра Амрин" },

{ lang: "Parachi (Iranian)", word: "اسرا امرین" },
{ lang: "Parya (Indo-Aryan)", word: "असरा अमरीन" },
{ lang: "Phalura (Indo-Aryan)", word: "असरा अमरीन" },
{ lang: "Phuthi (Bantu)", word: "Asra Amreen" },
{ lang: "Picard (Romance)", word: "Asra Amreen" },
{ lang: "Pig Latin", word: "Asray Amreenay" },
{ lang: "Pirahã (Mura)", word: "Asra Amreen" },
{ lang: "Polish (Slavic)", word: "Asra Amreen" },
{ lang: "Portuguese (Romance)", word: "Asra Amreen" },
{ lang: "Puelche (isolated)", word: "Asra Amreen" },
{ lang: "Puma (Tibeto-Burman)", word: "Asra Amreen" },

{ lang: "Quechua (Peru)", word: "Asra Amreen" },
{ lang: "Rajasthani (Indo-Aryan)", word: "असरा अमरीन" },
{ lang: "Romanian (Romance)", word: "Asra Amreen" },
{ lang: "Romany (Indo-Iranian)", word: "اسرا امرین" },
{ lang: "Rotokas (East Papuan)", word: "Asra Amreen" },
{ lang: "Russian (Slavic)", word: "Асра Амрин" },
{ lang: "Sadri (Indo-Aryan)", word: "असरा अमरीन" },
{ lang: "Salar (Turkic)", word: "Асра Амрин" },
{ lang: "Sandawe (Khoisan)", word: "Asra Amreen" },
{ lang: "Santali (Austroasiatic)", word: "ᱚᱥᱨᱟ ᱚᱢᱨᱤᱱ" },
{ lang: "Sara (Malayo-Polynesian)", word: "Asra Amreen" },
{ lang: "Sardinian (Romance)", word: "Asra Amreen" },
{ lang: "Sarikoli (Iranian)", word: "اسرا امرین" },
{ lang: "Savara (Dravidian)", word: "అస్రా అమ్రీన్" },
{ lang: "Savi (Indo-Aryan)", word: "असरा अमरीन" },
{ lang: "Sawai (Malayo-Polynesian)", word: "Asra Amreen" },
{ lang: "Semnani (Iranian)", word: "اسرا امرین" },
{ lang: "Senaya (Semitic)", word: "ܐܣܪܐ ܐܡܪܝܢ" },
{ lang: "Serbian (Slavic)", word: "Асра Амрин" },
{ lang: "Serbo-Croatian (Slavic)", word: "Asra Amreen" },
{ lang: "Sesotho (Bantu)", word: "Asra Amreen" },
{ lang: "Seto or Setu (Uralic)", word: "Asra Amreen" },
{ lang: "Shimaore (Bantu)", word: "Asra Amreen" },
{ lang: "Shina (Indo-Aryan)", word: "اسرا آمرین" },
{ lang: "Shona (Bantu)", word: "Asra Amreen" },
{ lang: "Shor (Turkic)", word: "Асра Амрин" },
{ lang: "Shoshoni (Uto-Aztecan)", word: "Asra Amreen" },
{ lang: "Shughni (Iranian)", word: "اسرا امرین" },
{ lang: "Shumashti (Indo-Aryan)", word: "असरा अमरीन" },
{ lang: "Shuswap (Salishan)", word: "Asra Amreen" },
{ lang: "Sicilian (Romance)", word: "Asra Amreen" },
{ lang: "Sidamo (Cushitic)", word: "Asra Amreen" },
{ lang: "Sika (Malayo-Polynesian)", word: "Asra Amreen" },
{ lang: "Silesian (Slavic)", word: "Asra Amreen" },
{ lang: "Sindhi (Indo-Aryan)", word: "اسرا آمرین" },
{ lang: "Sinhalese (Indo-Aryan)", word: "අස්රා අම්රීන්" },
{ lang: "Sioux (Siouan)", word: "Asra Amreen" },
{ lang: "Sivandi (Iranian)", word: "اسرا امرین" },
{ lang: "Skolt Sami (Uralic)", word: "Asra Amreen" },
{ lang: "Slavey (Athabaskan)", word: "Asra Amreen" },
{ lang: "Slovak (Slavic)", word: "Asra Amreen" },
{ lang: "Somali (Cushitic)", word: "Asra Amreen" },
{ lang: "Sonjo or Temi (Bantu)", word: "Asra Amreen" },
{ lang: "Soqotri (Semitic)", word: "اسرا آمرین" },
{ lang: "Sora (Austroasiatic)", word: "ଅସ୍ରା ଅମ୍ରୀନ୍" },
{ lang: "Sorbian, Lower (Slavic)", word: "Asra Amreen" },
{ lang: "Sorbian, Upper (Slavic)", word: "Asra Amreen" },
{ lang: "Sourashtra (Indo-Aryan)", word: "અસરા અમરીન" },
{ lang: "South Estonian (Uralic)", word: "Asra Amreen" },
{ lang: "Southern Sami (Uralic)", word: "Asra Amreen" },
{ lang: "Spanish (Romance)", word: "Asra Amreen" },
{ lang: "Standard Arabic", word: "اسرا آمرین" },
{ lang: "Suba (Bantu)", word: "Asra Amreen" },
{ lang: "Susu (Mande)", word: "Asra Amreen" },
{ lang: "Svan (South Caucasian)", word: "ასრა ამრინ" },
{ lang: "Swahili (Bantu)", word: "Asra Amreen" },
{ lang: "Swedish (Germanic)", word: "Asra Amreen" },
{ lang: "Syriac (Semitic)", word: "ܐܣܪܐ ܐܡܪܝܢ" },

{ lang: "Tachelhit (Berber)", word: "Asra Amreen" },
{ lang: "Tajik (Iranian)", word: "اسرا امرین" },
{ lang: "Takestani (Iranian)", word: "اسرا امرین" },
{ lang: "Talysh (Iranian)", word: "اسرا امرین" },
{ lang: "Tamil (Dravidian)", word: "அஸ்ரா அம்ரீன்" },
{ lang: "Tanacross (Athabaskan)", word: "Asra Amreen" },
{ lang: "Tangut (Tibeto-Burman)", word: "𗼇𗿧 𗼇𗿧" },
{ lang: "Tat or Tati (Iranian)", word: "اسرا امرین" },
{ lang: "Tatar (Turkic)", word: "Асра Амрин" },
{ lang: "Tehuelche (Chon)", word: "Asra Amreen" },
{ lang: "Telugu (Dravidian)", word: "అస్రా అమ్రీన్" },
{ lang: "Tetum (Malayo-Polynesian)", word: "Asra Amreen" },
{ lang: "Thai (Tai–Kadai)", word: "แอสรา อัมรีน" },
{ lang: "Tharu (Indo-Aryan)", word: "असरा अमरीन" },
{ lang: "Tibetan (Tibeto-Burman)", word: "ཨསྲ་ཨམྲིན" },
{ lang: "Tigre or Xasa (Semitic)", word: "አስራ አምሪን" },
{ lang: "Tigrinya (Semitic)", word: "አስራ አምሪን" },
{ lang: "Tiv (Benue–Congo)", word: "Asra Amreen" },
{ lang: "Tlingit (Na-Dené)", word: "Asra Amreen" },
{ lang: "Toda (Dravidian)", word: "அஸ்ரா அம்ரீன்" },
{ lang: "Tonga (Bantu)", word: "Asra Amreen" },
{ lang: "Tregami (Indo-Aryan)", word: "اسرا آمرین" },
{ lang: "Tsat (Malayo-Polynesian)", word: "Asra Amreen" },
{ lang: "Tsonga (Bantu)", word: "Asra Amreen" },
{ lang: "Tu or Monguor (Mongolic)", word: "ᠠᠰᠷᠠ ᠠᠮᠷᠢᠨ" },
{ lang: "Tulu (Dravidian)", word: "ಅಸ್ರಾ ಅಮ್ರೀನ್" },
{ lang: "Tumbuka (Bantu)", word: "Asra Amreen" },
{ lang: "Tupiniquim (Tupian)", word: "Asra Amreen" },
{ lang: "Turkish (Turkic)", word: "Asra Amreen" },
{ lang: "Turkmen (Turkic)", word: "Asra Amreen" },
{ lang: "Turoyo (Semitic)", word: "ܐܣܪܐ ܐܡܪܝܢ" },

{ lang: "Udmurt or Votyak (Uralic)", word: "Асра Амрин" },
{ lang: "Ukrainian (Slavic)", word: "Асра Амрін" },
{ lang: "Ulch or Olcha (Tungusic)", word: "Асра Амрин" },
{ lang: "Upper Sorbian (Slavic)", word: "Asra Amreen" },
{ lang: "Urdu (Indo-Aryan)", word: "اسرا آمرین" },
{ lang: "Urum (Turkic)", word: "Асра Амрин" },
{ lang: "Ute (Uto-Aztecan)", word: "Asra Amreen" },
{ lang: "Uyghur or Uigur (Turkic)", word: "ئاسرا ئامرېن" },
{ lang: "Uzbek (Turkic)", word: "Асра Амрин" },
{ lang: "Vafsi (Iranian)", word: "اسرا امرین" },
{ lang: "Valencian (Romance)", word: "Asra Amreen" },
{ lang: "Venetian (Romance)", word: "Asra Amreen" },
{ lang: "Veps (Uralic)", word: "Asra Amreen" },
{ lang: "Võro (Uralic)", word: "Asra Amreen" },
{ lang: "Votic or Votian (Uralic)", word: "Asra Amreen" },
{ lang: "Waddar (Dravidian)", word: "అస్రా అమ్రీన్" },
{ lang: "Wakhi (Iranian)", word: "اسرا امرین" },
{ lang: "Walloon (Romance)", word: "Asra Amreen" },
{ lang: "Washo (Hokan)", word: "Asra Amreen" },
{ lang: "Welsh (Celtic)", word: "Asra Amreen" },
{ lang: "Wolane (Silt’e) (Semitic)", word: "አስራ አምሪን" },
{ lang: "Wolof (Niger–Congo)", word: "Asra Amreen" },
{ lang: "Wu (Sinitic)", word: "阿斯拉 阿姆林" },

{ lang: "Xhosa (Bantu)", word: "Asra Amreen" },
{ lang: "Xiang (Sinitic)", word: "阿斯拉 阿姆林" },
{ lang: "Xibe or Sibo (Tungusic)", word: "Асра Амрин" },
{ lang: "Xipaya (Tupian)", word: "Asra Amreen" },
{ lang: "Yaaku language", word: "Asra Amreen" },
{ lang: "Yaeyama language", word: "アスラ アムリーン" },
{ lang: "Yaghnobi (Iranian)", word: "اسرا امرین" },
{ lang: "Yakut", word: "Асра Амрин" },
{ lang: "Yankunytjatjara language", word: "Asra Amreen" },
{ lang: "Yanomami", word: "Asra Amreen" },
{ lang: "Yanyuwa", word: "Asra Amreen" },
{ lang: "Yapese", word: "Asra Amreen" },
{ lang: "Yaqui", word: "Asra Amreen" },
{ lang: "Yauma (Bantu)", word: "Asra Amreen" },
{ lang: "Yavapai", word: "Asra Amreen" },
{ lang: "Yazdi (Iranian)", word: "اسرا امرین" },
{ lang: "Yemenite Hebrew (Semitic)", word: "אסרא אמרין" },
{ lang: "Yeni language", word: "Asra Amreen" },
{ lang: "Yevanic language", word: "Ασρα Αμριν" },
{ lang: "Yi language", word: "ꀉꌠ ꀉꂷꇋ" },
{ lang: "Yiddish (Germanic)", word: "אַסראַ אַמרין" },
{ lang: "Yidgha (Iranian)", word: "اسرا امرین" },
{ lang: "Yokutsan languages", word: "Asra Amreen" },
{ lang: "Yonaguni language", word: "アスラ アムリーン" },
{ lang: "Yorùbá language", word: "Asra Amreen" },
{ lang: "Yucatec Maya language", word: "Asra Amreen" },
{ lang: "Yuchi language", word: "Asra Amreen" },
{ lang: "Yukaghir languages", word: "Асра Амрин" },
{ lang: "Yurats language", word: "Asra Amreen" },
{ lang: "Yurok language", word: "Asra Amreen" },
{ lang: "Záparo (Saparoan)", word: "Asra Amreen" },
{ lang: "Zapotec (Oto-Manguean)", word: "Asra Amreen" },
{ lang: "Zazaki (Iranian)", word: "Asra Amreen" },
{ lang: "Zuñi or Zuni (isolated)", word: "Asra Amreen" },
{ lang: "Zway or Zay (Semitic)", word: "አስራ አምሪን" }


    
];

const container = document.getElementById("container");

data.forEach(item => {

    const div = document.createElement("div");
    div.className = "word";

    div.innerHTML = `
        ${item.word}
        <div class="tooltip">${item.lang}</div>
    `;

    container.appendChild(div);
});



